### PR TITLE
Data entry to Donations

### PR DESCRIPTION
**Pull request by tervelix**
I added all the data related to issues; #37, #30 , #20 , 

Added Arbitrum Network & Logo;
Added Ahbap's new adresses;
Added NeedsMap BtcTürk Adresses;
Added Communtty Volunteers Fountaion BtcTürk Adresses;
Added AFAD BtcTürk Adresses;
Added Bankless and Gnosis Giveth options;
Added giveth type and icon as svg;
Removed some unnecessary //Turkish text as the reffered links are english;
Added giveth OptionType;

### CODE REVIEW

**Comment by hantuzun** [comment]
Screen Shot 2023-02-14 at 00 58 12

Please fix the build first. A successful preview deployment is a must.

I suggest creating smaller pull requests. At this point, it'll be harder for you to figure out the source of the issue.

Have you run this on your computer?

**Comment by oytuncoban** [comment]
Hi @tervelix thanks for the Pull Request!

Unfortunately, you have made changes on an outdated version of main branch. When I tried to merge your branch into another updated branch, the addresses are conflicting on each other.

I'll suggest you to do the following:

- Fork another branch from main AFTER fetching the neu-fi/turkiye-relief-dao remote.
- Pull your changes from "Data-Entry-" branch. (You can use VS Code source control for that, it shows merge conflicts in a decent way).
- After the conflicts are resolved, we can merge the changes.

Please note that, new addresses should not be ordered manually. New addresses must be appended to the arrays. We shouldn't have deleted addresses in the changelog. I'll deploy another feature that sorts the addresses such that they are displayed in order. This way, the addresses that have the same networks appear together.

Beside all of that, thank you for you great efforts, @tervelix!

**Comment by oytuncoban** [comment]
I've reviewed the branch, done some necessary changes, merged with updated main branch. New pull request #88  is ready to go, I presume. I'm closing this pull request as it includes conflicting changes. Thank you, @tervelix!

**Comment by tervelix** [comment]
Thank u for ur lead guys. I actually resynced fork before i made changes but it is possible to i made some mistakes. Sorry for any conflicts. All data was there and i see @oytuncoban is already upload them. Thank u <3

**Pull request closed without merging**
