### PR TITLE
Mobile view

### LINKED ISSUE #6: Mobile view responsivity
Source links are hidden on mobile section.
I'm on it.

### PR DESCRIPTION
**Pull request by oytuncoban**

### CODE REVIEW

**Comment by hantuzun** [comment]
Screen Shot 2023-02-09 at 18 53 47

Makes it worse in some cases.

**Comment by oytuncoban** [comment]
> Screen Shot 2023-02-09 at 18 53 47
> 
> Makes it worse in some cases.

I'll change it to grid now,

**Comment by oytuncoban** [comment]
@hantuzun looks better now

**Comment by hantuzun** [comment]
Kindly remove the eslint workaround:
```
/* eslint-disable react/jsx-key */
```

**Comment by hantuzun** [comment]
Thanks for the fix, but there're more issues and the only valuable addition seems to be removing currency names on small screens. 

Here's a layout error:

Main:
Screen Shot 2023-02-10 at 22 41 16

PR:
Screen Shot 2023-02-10 at 22 41 22

I'll hide titles in a smaller commit and close this PR. Please open another PR with specific commit messages for what you change in CSS.

**Pull request closed without merging**
