### PR TITLE
done: #35 Persist filters state on page refreshes

### PR DESCRIPTION
**Pull request by zxselimcan**
image

### CODE REVIEW

**Comment by hantuzun** [comment]
Claims to fix #35.

**Comment by hantuzun** [comment]
This PR brings new errors to the console:
 * https://reactjs.org/docs/error-decoder.html/?invariant=423
 * https://reactjs.org/docs/error-decoder.html/?invariant=418

**Comment by zxselimcan** [comment]
> 

fixed it in: https://github.com/neu-fi/turkiye-relief-dao/pull/45/commits/ec4b935769f17cd5f42efeafac627e07c58bab5a

**Comment by hantuzun** [comment]
The filters are applied after the first render.

https://user-images.githubusercontent.com/2770895/218304285-2e054d7a-1c35-49cf-a16c-3c7ffd7e0632.mov

How can we fix that in this PR or another?

**Comment by hantuzun** [comment]
Opened https://github.com/neu-fi/turkiye-relief-dao/issues/50 and merged this.

**Pull request merged**
