### PR TITLE
Add Arbitrum and Optimism to Ahbap #37

### LINKED ISSUE #26: Add all BtcTurk matching options
All of the entries in https://pro.btcturk.com/deprem-bagis like the example in AFAD.

### LINKED ISSUE #37: Add Arbitrum and Optimism to Ahbap
Add the new bridged L2 assets to Ahbap.

### Arbitrum
 * https://twitter.com/ConnextNetwork/status/1624413520258379776
 * https://arbiscan.io/address/0x8888759373137b84e9f0ef13ecb13e321c251ee3#readContract
 
 ### Optimism
 * https://twitter.com/ConnextNetwork/status/1624413520258379776
 * https://optimistic.etherscan.io/address/0x8888759373137b84e9f0ef13ecb13e321c251ee3#readContract
 
 Add info: "Bridged through a trustless and audited contract"

### PR DESCRIPTION
**Pull request by oytuncoban**
Issue needs and BTCTurk wallet updates completed via #41.

Thanks @tervelix for the detailed information.

### CODE REVIEW

**Comment by hantuzun** [comment]
I removed #26 from this PR title as it's not covered.

**Review by hantuzun — CHANGES_REQUESTED** [review]
Please revert the order of other options.

Changing the data, especially the addresses of donation options is dangerous. The contributors and reviewers need to be very careful about that.

They should not be deleted in the diff and added to other points, forcing the reviewer to cross check all of them.

**Comment by hantuzun** [comment]
Otherwise, the contribution is flawless.

**Comment by oytuncoban** [comment]
> Please revert the order of other options.
> 
> Changing the data, especially the addresses of donation options is dangerous. The contributors and reviewers need to be very careful about that.
> 
> They should not be deleted in the diff and added to other points, forcing the reviewer to cross check all of them.

Done!

**Review by hantuzun — APPROVED** [review]

**Pull request merged**
