### PR TITLE
explorers added

### LINKED ISSUE #7: Add explorer links
The addresses should have blue pills just like the sources. They should be named "Explorer" and link to dynamically created explorer URLs.

### PR DESCRIPTION
**Pull request by oytuncoban**

### CODE REVIEW

**Comment by hantuzun** [comment]
1. Could you add the new networks in main?
2. The pill must be included next to the other pills.
3. Why did you edit the tooltip?

**Comment by oytuncoban** [comment]
> 1. Could you add the new networks in main?
> 2. The pill must be included next to the other pills.
> 3. Why did you edit the tooltip?

1. I'll adding now.
2. Nice idea!
3. On mobile it was overflowing outside the screen and couldn't be read.

**Comment by oytuncoban** [comment]
done!

**Comment by hantuzun** [comment]
I'll review it in an hour.

**Comment by hantuzun** [comment]
Since this PR depends on the previous PR I closed, I'll need to copy the work independently.

**Comment by hantuzun** [comment]
Thank you. I thanked you in the commit comment.

**Pull request closed without merging**
