### PR TITLE
Add Aptos Wallets

### PR DESCRIPTION
**Pull request by TeenaBatra**
This pull request proposes the integration of Aptos wallets as a new payment option for donations in the donations.ts file.
Additionally, Aptos icon is present in public/icons directory.

### CODE REVIEW

**Comment by hantuzun** [comment]
Thanks @TeenaBatra!

1. The icon should be round. 
2. The explorer's address URLs has the following format: https://explorer.aptoslabs.com/account/0x822fe5616e37b0f68db8c2f5198431267536fa9482ac744752444578138abbae Therefore, the account path must be added.

Could you fix these and test the look and the explorer links?

**Comment by TeenaBatra** [comment]
@hantuzun I've just updated the explorer's address url for aptos. Regarding the icon, I don't see the aptos icon in the repository link mentioned in the code(https://github.com/spothq/cryptocurrency-icons/tree/master/svg/color), So I downloaded the icon from the browser and used, Please advise where can I find the proper icon for Aptos.

**Comment by hantuzun** [comment]
Thanks for the URL. Let me check if the logo looks square first...

**Comment by hantuzun** [comment]
Yes, they're square...

**Comment by hantuzun** [comment]
Ok, I'll make them round programatically.

**Comment by hantuzun** [comment]
Thanks I merged, and made the icons round. Closed the issue now!

**Pull request merged**
