### PR TITLE
[#51]  Break the Donations component into sub-components and functions

### LINKED ISSUE #51: Break the Donations component into sub-components and functions
[Donations.tsx](https://github.com/neu-fi/turkiye-relief-dao/blob/main/app/Donations.tsx) is currently 600 lines.

The logic and the components better are broken down into sub-components and hooks and helper functions

The filters have duplicated code for mobile and desktop views. They better share their code.

### PR DESCRIPTION
**Pull request by yigitfindikli**
Fixed #51 - Break the Donations component into sub-components and functions

### CODE REVIEW

**Comment by hantuzun** [comment]
This's the first time I see this pattern for components:

```
const createBody = () => {
		return (<h1>Hello!</h1>);
};
const body = createBody();
return(<>{body}</>);
```

Isn't it better if we use components instead?

```
function Header() {
  return <h1>Hello!</h1>;
}
return(<><Header/></>);
```

This's still the best practice AFAIK: https://reactjs.org/docs/components-and-props.html

**Comment by yigitfindikli** [comment]
Actually, it's the same. Depends on your need.

**Comment by hantuzun** [comment]
They've the same functionality, but the latter is the convention. I kindly ask you to follow the conventional way that for compatibility with the rest of the code and make the code more familiar to all React.js developers.

**Review by oytuncoban — APPROVED** [review]

**Comment by hantuzun** [comment]
Thanks @yigitfindikli & @oytuncoban. This's way better than the big blob I initially built.

**Pull request merged**
