### PR TITLE
#5 fixed colors of icons in the footer

### PR DESCRIPTION
**Pull request by nhestrompia**
Fixed the color of icons in the footer to gray-400 and hover:gray-500. Also decreased the size of dune icon to match the other ones. Fixed layout.tsx for hydration error.

### CODE REVIEW

**Comment by hantuzun** [comment]
Claims to fix #5.

**Comment by hantuzun** [comment]
Thanks @nhestrompia!

1. This branch make the website overflow in small screen sizes. Could you make sure it doesn't overflow more than the deployment even in 375px width (iPhone SE)?

2. Could you change the colors of the Dune icon to fix the brightness of `gray-400 and hover:gray-500`?

**Comment by hantuzun** [comment]
@nhestrompia, I sent a collaboration request for the repo, so that I can assign issues.

**Comment by nhestrompia** [comment]
1. Checked the local branch for overflow in different sizes but couldn't find any bugs, looks same with the deployment.
2. Fixed dune colors to match with other icons

**Review by hantuzun — APPROVED** [review]
Thanks a lot, @nhestrompia. 

1. Yes, it was my bad. I tested it a couple of times but that was the behavior I have seen. Not this time. Brave inspect can fool us sometimes like that.
2. Looks perfect!

**Pull request merged**
