### PR TITLE
fix: update types and display count of filters

### PR DESCRIPTION
**Pull request by haticecs**
#1 
- update types
- display count
last-display

### CODE REVIEW

**Comment by hantuzun** [comment]
As I updated in #1 I prefer this text to be placed under the filters. What do you think?

**Comment by hantuzun** [comment]
There should not be `OrganizationName` type. It's a list of one-off parameters, not a type shared amongst data.

Adding new organizations will be more complicated as well.

**Comment by haticecs** [comment]
> As I updated in #1 I prefer this text to be placed under the filters. What do you think?
It makes sense to place there, let me update

**Comment by haticecs** [comment]
> There should not be `OrganizationName` type. It's a list of one-off parameters, not a type shared amongst data.
> Adding new organizations will be more complicated as well.
I think that it is more type-safe, when someone adds a new organization, it should be added to the type. However, I can convert it to the string ofc.

**Comment by haticecs** [comment]
Screenshot 2023-02-12 at 18 46 50 (2)
Screenshot 2023-02-12 at 18 46 40 (2)
I've updated it, and removed the OrganizationName type.

**Comment by hantuzun** [comment]
> I think that it is more type-safe, when someone adds a new organization, it should be added to the type. However, I can convert it to the string ofc.

Organization names are not types. There's no set of Organization names. There isn't any use case where it makes a program safer to check if a string is a valid OrganizationName.

**Comment by hantuzun** [comment]
Thank you for the clear PR and for taking my feedback into account.

Everything is OK, except the mobile view. I'll open a new issue for that and assign you @haticecs. Thanks a lot.

**Review by hantuzun — APPROVED** [review]
Works except the mobile view.

**Pull request merged**
