### PR TITLE
fixes #17 display sort dropdown

### LINKED ISSUE #17: Sorting organizations functionality
1. The sort dropdown is commented out. Enable that to make sure it looks fine on screens as narrow as 375px (iPhone SE).
2. Add 2 options: "Suggested" (default), "Popular"

Suggested: The order of the array, which is the current implementation.
Popular: Sorted by the popularity parameters.

### PR DESCRIPTION
**Pull request by haticecs**
#17 
It looks like this on the iPhone SE.
The functionality works as expected (see gif)
Screenshot 2023-02-13 at 23 54 11 (2)
sort

### CODE REVIEW

**Comment by hantuzun** [comment]
Thanks a lot. I had to verify all the addresses. Please create atomic PRs the next time.

**Review by hantuzun — DISMISSED** [review]
lgtm. the addresses had to be verified.

**Comment by hantuzun** [comment]
Hatice, you have force pushed a new commit. Now I cannot merge this PR. Because I need to review all the addresses again.

**Comment by hantuzun** [comment]
This is what a malicious contributor would do. Wait for a passing review. The moment the maintainer is about to merge. Then, force push with malicious addresses. 

I know you are not dishonest, but a malicious contributor would be doing just the same.

In general, please do not force push.

@oytuncoban, could you review all the functionality and the addresses? I assign you as the reviewer.

**Comment by haticecs** [comment]
@hantuzun 
I didn't see the review has been done and forced with the` --with-lease` flag. The reason for it is that I `amend` the commit message since I wanted to fix the white space changes (they are not real changes). I am sorry for the inconvenience and for taking your time. I will not force it next time, and prefer the `merge` instead of `rebase`.

**Comment by hantuzun** [comment]
Thanks for your understanding @haticecs. It's not personal, I'm just responsible for maintaining this website. Part of it is enforcing a development process resilient against malicious actors. Scammers are already targeting us: https://twitter.com/turkiyreliefdao

Unfortunately, the PR will need to wait for @oytuncoban.

The good news; is we did not have the popularity and suggestions decided. A friend of mine is working on that. The PR will be live with actually suggested and actually popular data.

**Comment by haticecs** [comment]
I see now 👍🏼, @hantuzun  
I noticed `donation.ts` is updated by prettier. I am gonna update this part so that pr won't be huge for @oytuncoban as well. 
The incoming changes sound exciting, can't wait.

**Review by hantuzun — APPROVED** [review]
Thanks for the fix. Thanks also for not including a prettier changes in an unrelated PR.

**Pull request merged**
